
GET http://localhost:3000/api/members


###
GET http://localhost:3000/api/members/3

###

GET http://localhost:3000/api/members?team=Customer%20Success

### 

POST http://localhost:3000/api/members 
Content-Type:application/json

{ 
  "id": 10, 
  "name": "Sojeen", 
  "team": "Customer Success", 
  "position": "Team Lead", 
  "emailAddress": "sojeen@ab180.co"
}


###


PUT http://localhost:3000/api/members/8
Content-Type:application/json

{ 
  "team" : "Sales"
}

###

DELETE http://localhost:3000/api/members/10
