GET http://127.0.0.1:3000/api/members


### 

POST http://52.78.205.70/api/members
Content-Type : application/json

{
  "id": 10, 
  "name": "sojeen", 
  "team": "Customer Success", 
  "position" : "Team Lead", 
  "emailAddress" : "sojeen@ab180.co"  
}

###

POST http://52.78.205.70/api/members
Content-Type: application/json

{
  "id": 10,
  "name": "sojeen",
  "team": "Customer Success",
  "position" : "Team Lead",
  "emailAddress" : "sojeen@ab180.co"
}


###
PUT http://localhost:3000/api/members/3 
Content-Type : application/json

{
  "team" : "CS"  
}


###
PUT http://localhost:3000/api/members/3
Content-Type : application/json

{
  "team" : "enablement"  
}

###
DELETE http://52.78.205.70/api/members


